input {
  kafka {
    bootstrap_servers => "kafka:29092"
    topics            => ["app-logs"]
    codec             => json
    auto_offset_reset => "earliest"
    group_id          => "logstash-consumer"
  }
}

filter {
  date {
    match => ["@timestamp", "yyyy-MM-dd'T'HH:mm:ss.SSSZ", "ISO8601"]
    target => "@timestamp"
  }

  # Promote a few fields Kibana will filter on most
  mutate {
    rename => { "level"       => "log_level" }
    rename => { "logger_name" => "logger" }
    rename => { "thread_name" => "thread" }
  }
}

output {
  opensearch {
    hosts => ["http://opensearch:9200"]
    index => "app-logs-%{+YYYY.MM.dd}"
  }
}